/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ferrari.glb
Author: ᗩᒪE᙭. Kᗩ.🚗 (https://sketchfab.com/Alex.Ka.)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/ferrari-550-barchetta-2000-azzurro-hyperion-202a1164d837454ca2e829a9c0e6935f
Title: Ferrari 550 Barchetta 2000 Azzurro Hyperion
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useControls } from "leva";

export function Ferrari(props) {
  const bodyMat = new THREE.MeshStandardMaterial({
    color: props.color.body,
    roughness: 0.3,
    metalness: 0.7,
  });
  const tireMat = new THREE.MeshStandardMaterial({
    color: props.color.tire,
  });
  const rimMat = new THREE.MeshStandardMaterial({
    color: props.color.rim,
  });

  const { nodes, materials } = useGLTF("./models/ferrari.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.11}>
        {
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials["550bachetta"]}
          />
        }
        {/* Body */}
        <mesh geometry={nodes.Object_3.geometry} material={bodyMat} />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.PLdiffuser}
        />
        <mesh geometry={nodes.Object_5.geometry} material={materials.PLhood} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.PLskirt} />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.PLsplitter}
        />

        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.blackaluminium}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.blackchrome}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.blackmatte}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.blackplastic}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.boltschrome}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.boltsplastic}
        />
        <mesh geometry={nodes.Object_15.geometry} material={materials.bottom} />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.brakedisk}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.brakelghtOFF}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.brakelghtON}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.centrbrakelight}
        />
        <mesh geometry={nodes.Object_20.geometry} material={materials.chrome} />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.designo}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.detailschrome}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.detailsmatte}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.detailsplastic}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.exhaust}
        />
        <mesh
          geometry={nodes.Object_26.geometry}
          material={materials.exhaustbronze}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.exhausthole}
        />
        <mesh
          geometry={nodes.Object_28.geometry}
          material={materials.ferrarisupportlogo}
        />
        <mesh
          geometry={nodes.Object_30.geometry}
          material={materials.floormat}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.foglight}
        />
        <mesh
          geometry={nodes.Object_32.geometry}
          material={materials.foglightglass}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.frontbumpvent}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.fuelcap}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.grillrearexh}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.grillside}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.headlight1}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.headlight2}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.headlightglass}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.headlightplastic}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.headlightturnsignal}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials.hoodemblem}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.hoodgrill}
        />
        <mesh geometry={nodes.Object_44.geometry} material={materials.horse} />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.interior}
        />
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.interiorchrome}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.interiorplastic}
        />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.mirrorint}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.mirrorside}
        />
        <mesh
          geometry={nodes.Object_50.geometry}
          material={materials.pininfarina}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.plateFRONT}
        />
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials.plateREAR}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials.plateblackplastic}
        />
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials.platecarname}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.plateitalylogo}
        />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials.platelightlamp}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.radiator}
        />
        <mesh geometry={nodes.Object_58.geometry} material={rimMat} />
        <mesh geometry={nodes.Object_59.geometry} material={rimMat} />
        <mesh
          geometry={nodes.Object_60.geometry}
          material={materials.rimbolts1}
        />
        <mesh
          geometry={nodes.Object_61.geometry}
          material={materials.rimbolts2}
        />
        <mesh
          geometry={nodes.Object_62.geometry}
          material={materials.rimlogo}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.safecage}
        />
        <mesh
          geometry={nodes.Object_64.geometry}
          material={materials.seatbelt}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.sidehorseemblem}
        />
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials.sideturnsignals}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.sidewindowHORSE}
        />
        <mesh
          geometry={nodes.Object_68.geometry}
          material={materials.splitergril}
        />
        <mesh
          geometry={nodes.Object_69.geometry}
          material={materials.steeringwheel}
        />
        <mesh
          geometry={nodes.Object_70.geometry}
          material={materials.support1}
        />
        <mesh
          geometry={nodes.Object_71.geometry}
          material={materials.support2}
        />
        {/* Tire */}
        <mesh geometry={nodes.Object_72.geometry} material={tireMat} />
        <mesh
          geometry={nodes.Object_73.geometry}
          material={materials.tireprotector}
        />
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials.underHOODbolt}
        />
        <mesh
          geometry={nodes.Object_75.geometry}
          material={materials.underHOODplastic}
        />
        <mesh
          geometry={nodes.Object_76.geometry}
          material={materials.wheelblack}
        />
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials.windowF}
        />
        <mesh
          geometry={nodes.Object_78.geometry}
          material={materials.windowFinside}
        />
        <mesh
          geometry={nodes.Object_79.geometry}
          material={materials.windowS}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.windowSinside}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/ferrari.glb");
