/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/garage.glb
Author: Dogus ß ô â (https://sketchfab.com/Dogus.Berk.Bayram)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/garage-warehouse-316c4f801e274662a61e74e1cb25ea52
Title: Garage / Warehouse
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Garage(props) {
  const { nodes, materials } = useGLTF("./models/garage.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Demirler}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Duvarlar}
        />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Odunlar} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Tavan} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Zemin} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.ipler} />
      </group>
    </group>
  );
}

useGLTF.preload("./models/garage.glb");
