/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/lambo1.glb
Author: Jonrss (https://sketchfab.com/huy14320000006)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lamborghini-venevo-5884f95259ff411c95510cdde5ede33e
Title: Lamborghini venevo
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lambo1(props) {
  const { nodes, materials } = useGLTF("./models/lambo1.glb");
  return (
    <group {...props} dispose={null}>
      <group
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      >
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Vt_Liu.002"]}
        />
      </group>
      <group
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      >
        <mesh geometry={nodes.Object_15.geometry} material={materials.lamp} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Vt_Liu} />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials["Vt_Liu.001"]}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.engine}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.material}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.wheel}
        position={[0.91, 1.32, -4.52]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.65, 3.65, 3.65]}
      />
      <mesh
        geometry={nodes.Object_13.geometry}
        material={materials.material_5}
        position={[0.91, 1.32, -4.52]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.65, 3.65, 3.65]}
      />
      <mesh
        geometry={nodes.Object_19.geometry}
        material={materials.material_9}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_21.geometry}
        material={materials.material_10}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.material_11}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.material_12}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials.glass}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.material_14}
        position={[0.89, 1.33, -5.2]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.65, 3.65, 3.65]}
      />
      <mesh
        geometry={nodes.Object_31.geometry}
        material={materials.material_15}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_33.geometry}
        material={materials.logo}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_35.geometry}
        material={materials.material_17}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_37.geometry}
        material={materials.material_18}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_39.geometry}
        material={materials.material_19}
        position={[0.89, 1.33, -5.2]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.65, 3.65, 3.65]}
      />
      <mesh
        geometry={nodes.Object_41.geometry}
        material={materials.glass}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_43.geometry}
        material={materials.material_20}
        position={[-1.72, 0.5, 0.05]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.37, 3.37, 3.37]}
      />
      <mesh
        geometry={nodes.Object_45.geometry}
        material={materials.wheel}
        position={[1.27, 1.18, 4.53]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.27, 3.27, 3.27]}
      />
      <mesh
        geometry={nodes.Object_47.geometry}
        material={materials.material_5}
        position={[1.27, 1.18, 4.53]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.27, 3.27, 3.27]}
      />
      <mesh
        geometry={nodes.Object_49.geometry}
        material={materials.material_14}
        position={[1.25, 1.19, 4]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.03, 3.03, 3.03]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.material_19}
        position={[1.25, 1.19, 4]}
        rotation={[1.58, 0, -0.03]}
        scale={[-3.03, 3.03, 3.03]}
      />
    </group>
  );
}

useGLTF.preload("./models/lambo1.glb");
